build: off
version: '{build}'
image: Visual Studio 2017
environment:
  nodejs_version: 8
cache:
  - '%LOCALAPPDATA%\Yarn'
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install --frozen-lockfile
test_script:
  - yarn test
  - yarn run build all
