environment:
  matrix:
    - nodejs_version: '5'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@latest || (timeout 30 && npm install -g npm@latest)
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install || (timeout 30 && npm install)
matrix:
  fast_finish: true
build: off
version: '{build}'
clone_depth: 1
test_script:
  - npm test
  - npm run build -- node
  - node dist/node/loader.js
